<h1>defaultModule index/index.phtml</h1>
<div class="ui breadcrumb">
	<a class="section">Home</a> <i class="right chevron icon divider"></i>
	<a class="section">Registration</a> <i class="right arrow icon divider"></i>
	<div class="active section">Personal Information</div>
</div>

<div class="ui divider"></div>

<div class="filtering">
	<form>
		<div class="ui action left icon input">
			<i class="search icon"></i> <input placeholder="Search..."
				type="text">
			<div class="ui teal button">Search</div>
		</div>
	</form>
</div>

<div class="ui divider"></div>

<div id="PersonTableContainer"></div>
<table class="ui table" id="mytable">
	<thead>
		<tr>
			<th></th>
			<th>id</th>
			<th>name</th>
			<th>password</th>
		</tr>
	</thead>
	<tbody>
		<tr id="tr1">
			<td class="collapsing">
				<div class="ui fitted slider checkbox">
					<input type="checkbox" reference="tr1"> <label></label>
				</div>
			</td>

			<td>test</td>
			<td>test</td>
			<td>test</td>
		</tr>

		<tr>
			<td class="collapsing">
				<div class="ui fitted slider checkbox">
					<input type="checkbox"> <label></label>
				</div>
			</td>

			<td>test</td>
			<td>test</td>
			<td>test</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th colspan="4">
				<div class="ui right floated pagination menu">
					<a class="icon item"> <i class="left chevron icon"></i>
					</a> <a class="item">1</a> <a class="item">2</a> <a
						class="item active teal">3</a> <a class="item">4</a> <a
						class="icon item"> <i class="right chevron icon"></i>
					</a>
				</div>
			</th>
		</tr>
	</tfoot>
</table>
<?php echo $this->getContent(); ?>