 <div class="ui stackable grid">
	<div class="row">
		<div class="black sixteen wide column centered">
			<h1 class="header">Hello Thunderhawk !</h1>
		</div>
	</div>
	<div class="row">
		<div class="twelve wide column centered">
			<?php echo $this->getContent() ;?>
		</div>
	</div>
	<div class="row">
		<div class="black sixteen wide column centered">
			<h1 class="header">footer</h1>
		</div>
	</div>
</div>