 <div class="ui stackable grid">
	<div class="row">
		<div class="black sixteen wide column centered">
			<?php $this->partial('header');?>
		</div>
	</div>
	<div class="row">
		<div class="twelve wide column centered">
			<?php $this->partial('content');?>
		</div>
	</div>
	<div class="row">
		<div class="black sixteen wide column centered">
			<?php $this->partial('footer');?>
		</div>
	</div>
</div>