<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<?php echo $this->tag->getTitle();?>
		<?php echo $this->assets->outputJQuery(); ?>
		<?php echo $this->assets->outputJQueryUI(); ?>
		
		<?php echo $this->assets->outputCustomCss(); ?>
		<?php echo $this->assets->outputCss(); ?>
		
		<?php echo $this->assets->outputCustomJs(); ?>
		<?php echo $this->assets->outputJs(); ?>
		
		
	</head>
	<body>
		<?php echo $this->getContent() ;?>
	</body>
</html>