<!DOCTYPE html>
<html ng-app="thunderhawk">
	<head>
		<meta charset="utf-8">
		
		<?php echo $this->tag->getTitle();?>
		
		<?php echo $this->assets->outputJquery(); ?>
		<?php echo $this->assets->outputJqueryui(); ?>
		
		<?php echo $this->assets->outputAngular(); ?>
		
		<?php echo $this->assets->outputSemantic(); ?>
		
		<?php echo $this->assets->outputCss(); ?>
		<?php echo $this->assets->outputJs(); ?>
		
		<?php echo $this->assets->outputCustomCss(); ?>
		<?php echo $this->assets->outputCustomJs(); ?>
		
	</head>
	<body>
		<?php echo $this->getContent() ;?>
	</body>
</html>
